server:
  port: 8090
  servlet:
    context-path: /app
    session:
      timeout: 15m

jwt:
  secret: veysecretsecret

spring:
  h2:
    console:
      enabled: true
  datasource:
    sqlScriptEncoding: UTF-8
    platform: h2
    initialize: true
    username: f1user
    password: f1user
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/data/f1test
  jpa:
    hibernate:
      ddl-auto: create-drop
      connection:
        charSet: UTF-8
      hbm2ddl:
        import_files_sql_extractor=org:
          hibernate:
            tool:
              hbm2ddl: MultipleLinesSqlCommandExtractor


    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    open-in-view: false

logging:
  level:
    root: INFO


